#QA Automation-Partner Marketplace add benefithub_url = "http://10.140.0.175:4444/wd/hub"
downloads_directory = "test_data/downloads"
server_count = "4"
organization = "QA Automation - Create New Employee"
organization_username = "QA_Automation-CreateNewEmployee_Admin01"
organization_password = "QA_Automation-CreateNewEmployee_Admin01-password"
root_username = "qa_automation"
root_password = "qa_automation01"
production_root_username = "qa_automation"
production_root_password = "qa_automation01"
edi_base_organization = "QA Automation- EDI Base"
edi_base_administrator_username = "qa_automation_edi_base"
edi_base_administrator_password = "Automation01"
edi_base2_organization = "QA Automation- EDI Base 2"
edi_base2_administrator_username = "QA_Automation-EDI2_Admin01"
edi_base2_administrator_password = "QA_Automation-EDI2_Admin01-password"
edi_wse_organization = "QA Automation - WSE Processing"
admin_workflow_base_organization = "QA Automation- Admin Workflow Base"
admin_workflow_base_username = "admin_workflow_base_admin"
admin_workflow_base_password = "Automation01"
subscriber_username = "nprecio2020"
subscriber_password = "nprecio2020_password"
subscriber_username_ui2 = "subscriber_2"
subscriber_password_ui2 = "subs12345"
admin_workflow_base = "QA Automation - admin workflow base"

[base_urls]
benefits = "https://www.booking.com/"
broker = "https://benefits.plansourcetest.com/broker"
admin = "https://benefits.plansourcetest.com/ops-admin"
ulti_pro_login = "https://plansweb.ultiproservices.com/"
ulti_pro_prod_demo_login = "https://et24.ultipro.com/Login.aspx"
partner_dev = "https://partner-dev-benefits.plansource.com"
bamboo_sandbox = "https://plansourcesandbox.bamboohr.com/"
clearinghouse = "https://834clearinghouse.plansourcetest.com/"
plansweb = "https://plansweb.ultiproservices.com/"
keycloak = "https://sso.plansourcetest.com"
analytics = "https://analytics.plansourcetest.com"
api = "https://api.plansourcetest.com"
FAP_generate_credentials = "https://apisvc.glic.com/api/v1/cc/oauth2/token/generate"
FAP_guardian_search_results = "https://apisvc.glic.com/FAPAPI-Ext-v1/api/ppoprovider/SearchResult"
HCM_dashboard = "https://hcmdashboard.plansourcetest.com/#/"
the_source_pages = "https://benefits.plansourcetest.com/plan_source/ben_admin/the_source"
